apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-worker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo-worker
  template:
    metadata:
      labels:
        app: demo-worker
    spec:
      containers:
      - name: demo-worker
        image: 172.30.212.89:30500/demo-worker:v1
        imagePullPolicy: IfNotPresent
        env:
        - name: Redis__ConnectionString
          value: "redis-service:6379"