apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: demo-api
  template:
    metadata:
      labels:
        app: demo-api
    spec:
      containers:
        - name: demo-api
          image: "{{ .Values.image.dockerhubUser }}/demo-api:{{ .Values.image.tag }}"
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          env:
            - name: Redis__ConnectionString
              value: "redis-service:6379"
            - name: ASPNETCORE_ENVIRONMENT
              value: "{{ .Values.environment }}"
