apiVersion: v1
kind: Service
metadata:
  name: api-service
  annotations:
    prometheus.io/scrape: "true" # 告訴 Prometheus 目標
    prometheus.io/port: "8080" # 指標端點所在的 Port
    prometheus.io/path: "/metrics" # 指標路徑
spec:
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
  selector:
    app: demo-api
    app.kubernetes.io/component: api
