apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-worker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo-worker
  template:
    metadata:
      labels:
        app: demo-worker
    spec:
      containers:
        - name: demo-worker
          image: "{{ .Values.image.dockerhubUser }}/demo-worker:{{ .Values.image.tag }}"
          imagePullPolicy: IfNotPresent
          env:
            - name: Redis__ConnectionString
              value: "redis-service:6379"
